# Generated by Django 5.2.12 on 2026-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
